version: "3.7"

services:
  n8n:
    build:
      context: ./n8n
      dockerfile: Dockerfile
      args:
        N8N_VERSION: "1.103.2"
    container_name: n8n
    restart: always
    ports:
      - "0.0.0.0:5678:5678"
    environment:
      - N8N_HOST=xx.pogorelyi.com
      - N8N_PORT=5678
      - WEBHOOK_URL=https://xx.pogorelyi.com/
      - N8N_PROTOCOL=https
      - N8N_PUSH_BACKEND=websocket
      - NODE_ENV=production
      - GENERIC_TIMEZONE=Europe/Berlin
      - NODE_FUNCTION_ALLOW_BUILTIN=https,crypto
      - NODE_FUNCTION_ALLOW_EXTERNAL=moment,lodash,web3,ccxt,ethers,axios,@clickhouse/client
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=n8n_production
      - DB_POSTGRESDB_USER=n8n_production
      - DB_POSTGRESDB_PASSWORD=YOUR_PASSWORD
    depends_on:
      - postgres
    volumes:
      - n8n_data:/home/node/.n8n
    networks:
      - n8n_network
  postgres:
    image: postgres:16.2
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres-volume-n8n:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: YOUR_PASSWORD
      POSTGRES_USER: n8n_production
      POSTGRES_DB: n8n_production
    networks:
      - n8n_network

volumes:
  n8n_data:
  postgres-volume-n8n:

networks:
  n8n_network:
    driver: bridge
